// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6dnt45JBjJD93NLIeilPo86CnUr791hs',
    appId: '1:380200305804:web:023d18b5400e0f732de7a9',
    messagingSenderId: '380200305804',
    projectId: 'dine-7973e',
    authDomain: 'dine-7973e.firebaseapp.com',
    storageBucket: 'dine-7973e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa69JsmNG65p7Hdiesa8BeO0GzUQ8xwK0',
    appId: '1:380200305804:android:154574d30f1e0d4a2de7a9',
    messagingSenderId: '380200305804',
    projectId: 'dine-7973e',
    storageBucket: 'dine-7973e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_b7cUYA82hULrxr84-OrjS3vII25_G_k',
    appId: '1:380200305804:ios:b1e32f98bf94702e2de7a9',
    messagingSenderId: '380200305804',
    projectId: 'dine-7973e',
    storageBucket: 'dine-7973e.appspot.com',
    iosClientId: '380200305804-2o8kfqr9jubaditvkof7v0h7uo2pneaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.dine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_b7cUYA82hULrxr84-OrjS3vII25_G_k',
    appId: '1:380200305804:ios:b1e32f98bf94702e2de7a9',
    messagingSenderId: '380200305804',
    projectId: 'dine-7973e',
    storageBucket: 'dine-7973e.appspot.com',
    iosClientId: '380200305804-2o8kfqr9jubaditvkof7v0h7uo2pneaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.dine',
  );
}
